from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class NewBook(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, title=None, author=None, published_year=None, genre=None):  # noqa: E501
        """NewBook - a model defined in OpenAPI

        :param title: The title of this NewBook.  # noqa: E501
        :type title: str
        :param author: The author of this NewBook.  # noqa: E501
        :type author: str
        :param published_year: The published_year of this NewBook.  # noqa: E501
        :type published_year: int
        :param genre: The genre of this NewBook.  # noqa: E501
        :type genre: str
        """
        self.openapi_types = {
            'title': str,
            'author': str,
            'published_year': int,
            'genre': str
        }

        self.attribute_map = {
            'title': 'title',
            'author': 'author',
            'published_year': 'publishedYear',
            'genre': 'genre'
        }

        self._title = title
        self._author = author
        self._published_year = published_year
        self._genre = genre

    @classmethod
    def from_dict(cls, dikt) -> 'NewBook':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NewBook of this NewBook.  # noqa: E501
        :rtype: NewBook
        """
        return util.deserialize_model(dikt, cls)

    @property
    def title(self) -> str:
        """Gets the title of this NewBook.


        :return: The title of this NewBook.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this NewBook.


        :param title: The title of this NewBook.
        :type title: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title

    @property
    def author(self) -> str:
        """Gets the author of this NewBook.


        :return: The author of this NewBook.
        :rtype: str
        """
        return self._author

    @author.setter
    def author(self, author: str):
        """Sets the author of this NewBook.


        :param author: The author of this NewBook.
        :type author: str
        """
        if author is None:
            raise ValueError("Invalid value for `author`, must not be `None`")  # noqa: E501

        self._author = author

    @property
    def published_year(self) -> int:
        """Gets the published_year of this NewBook.


        :return: The published_year of this NewBook.
        :rtype: int
        """
        return self._published_year

    @published_year.setter
    def published_year(self, published_year: int):
        """Sets the published_year of this NewBook.


        :param published_year: The published_year of this NewBook.
        :type published_year: int
        """
        if published_year is None:
            raise ValueError("Invalid value for `published_year`, must not be `None`")  # noqa: E501

        self._published_year = published_year

    @property
    def genre(self) -> str:
        """Gets the genre of this NewBook.


        :return: The genre of this NewBook.
        :rtype: str
        """
        return self._genre

    @genre.setter
    def genre(self, genre: str):
        """Sets the genre of this NewBook.


        :param genre: The genre of this NewBook.
        :type genre: str
        """

        self._genre = genre
