# coding: utf-8

"""
    Simple Books API

    Simple Books Management API with Flask.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.books_api import BooksApi


class TestBooksApi(unittest.TestCase):
    """BooksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BooksApi()

    def tearDown(self) -> None:
        pass

    def test_books_get(self) -> None:
        """Test case for books_get

        List books
        """
        pass

    def test_books_id_delete(self) -> None:
        """Test case for books_id_delete

        Delete a book
        """
        pass

    def test_books_id_get(self) -> None:
        """Test case for books_id_get

        Get a book by ID
        """
        pass

    def test_books_id_put(self) -> None:
        """Test case for books_id_put

        Update a book
        """
        pass

    def test_books_post(self) -> None:
        """Test case for books_post

        Create a book
        """
        pass


if __name__ == '__main__':
    unittest.main()
