# coding: utf-8

"""
    Simple Books API

    Simple Books Management API with Flask.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.new_book import NewBook

class TestNewBook(unittest.TestCase):
    """NewBook unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NewBook:
        """Test NewBook
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NewBook`
        """
        model = NewBook()
        if include_optional:
            return NewBook(
                title = 'Clean Code',
                author = 'Robert C. Martin',
                published_year = 2008,
                genre = 'Software Engineering'
            )
        else:
            return NewBook(
                title = 'Clean Code',
                author = 'Robert C. Martin',
                published_year = 2008,
        )
        """

    def testNewBook(self):
        """Test NewBook"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
